src/SurveyBundle/Entity/Survey.php
<?php

namespace SurveyBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Survey
 *
 * @ORM\Table(name="survey")
 * @ORM\Entity(repositoryClass="SurveyBundle\Repository\SurveyRepository")
 */
class Survey
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\User",inversedBy="survey_id",cascade={"persist"})
     * @ORM\JoinColumn(name="user_id",referencedColumnName="id")
     */
    private $user_id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="send_date",type="datetime")
     */
    private $send_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="open_date",type="datetime",nullable=true)
     */
    private $open_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="vote_date",type="datetime",nullable=true)
     */
    private $vote_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_date",type="datetime",nullable=true)
     */
    private $resend_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_open_date",type="datetime",nullable=true)
     */
    private $resend_open_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_vote_date",type="datetime",nullable=true)
     */
    private $resend_vote_date;

    /**
     * @var int
     * @ORM\Column(name="ticket_id",type="integer",length=11,nullable=true)
     */
    private $ticket_id;

    /**
     * @var int
     * @ORM\Column(name="post_id",type="integer",length=11,nullable=true)
     */
    private $post_id;

    /**
     * @var int
     * @ORM\Column(name="client_id",type="integer",length=11,nullable=true)
     */
    private $client_id;

    /**
     * @var string
     * @ORM\Column(name="client_email",type="string")
     */
    private $client_email;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyType",inversedBy="survey",cascade={"persist"})
     * @ORM\JoinColumn(name="survey_type",referencedColumnName="id")
     */
    private $survey_type;

    /**
     * @var string
     * @ORM\Column(name="checksum",type="string")
     */
    private $checksum;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\Rate",inversedBy="survey")
     * @ORM\JoinColumn(name="rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $rate;

    /**
     * @var SurveyStaffRate
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyStaffRate",inversedBy="survey")
     * @ORM\JoinColumn(name="staff_rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $staff_rate;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\Rate",inversedBy="survey_resend")
     * @ORM\JoinColumn(name="resend_rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $resend_rate;

    /**
     * @var SurveyStaffRate
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyStaffRate",inversedBy="survey_second")
     * @ORM\JoinColumn(name="resend_staff_rate",referencedColumnName="id",columnDefinition=" INT NULL")
     */
    private $resend_staff_rate;

    /**
     * @var string
     * @ORM\Column(name="comment",type="text",nullable=true)
     */
    private $comment;

    /**
     * @var string
     * @ORM\Column(name="resend_comment",type="text",nullable=true)
     */
    private $resend_comment;

    /**
     * @var string
     * @ORM\Column(name="user_comment",type="text",nullable=true)
     */
    private $user_comment;

    /**
     * @var boolean
     * @ORM\Column(name="cancel",type="boolean",nullable=true)
     */
    private $cancel;

    /**
     * @var string
     * @ORM\Column(name="admin_comment",type="text",nullable=true)
     */
    private $admin_comment;

    /**
     * @ORM\OneToOne(targetEntity="SurveyBundle\Entity\SurveyResend",mappedBy="survey")
     */
    private $resend;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param User $user_id
     *
     * @return mixed
     */
    public function setUserId(\SurveyBundle\Entity\User $user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getSendDate()
    {
        return $this->send_date;
    }

    /**
     * @param \DateTime $send_date
     */
    public function setSendDate($send_date)
    {
        $this->send_date = $send_date;
    }

    /**
     * @return \DateTime
     */
    public function getOpenDate()
    {
        return $this->open_date;
    }

    /**
     * @param \DateTime $open_date
     */
    public function setOpenDate($open_date)
    {
        $this->open_date = $open_date;
    }

    /**
     * @return \DateTime
     */
    public function getVoteDate()
    {
        return $this->vote_date;
    }

    /**
     * @param \DateTime $vote_date
     */
    public function setVoteDate($vote_date)
    {
        $this->vote_date = $vote_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendDate()
    {
        return $this->resend_date;
    }

    /**
     * @param \DateTime $resend_date
     */
    public function setResendDate($resend_date)
    {
        $this->resend_date = $resend_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendOpenDate()
    {
        return $this->resend_open_date;
    }

    /**
     * @param \DateTime $resend_open_date
     */
    public function setResendOpenDate($resend_open_date)
    {
        $this->resend_open_date = $resend_open_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendVoteDate()
    {
        return $this->resend_vote_date;
    }

    /**
     * @param \DateTime $resend_vote_date
     */
    public function setResendVoteDate($resend_vote_date)
    {
        $this->resend_vote_date = $resend_vote_date;
    }

    /**
     * @return int
     */
    public function getTicketId()
    {
        return $this->ticket_id;
    }

    /**
     * @param int $ticket_id
     */
    public function setTicketId($ticket_id)
    {
        $this->ticket_id = $ticket_id;
    }

    /**
     * @return int
     */
    public function getPostId()
    {
        return $this->post_id;
    }

    /**
     * @param int $post_id
     */
    public function setPostId($post_id)
    {
        $this->post_id = $post_id;
    }

    /**
     * @return int
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * @param int $client_id
     */
    public function setClientId($client_id)
    {
        $this->client_id = $client_id;
    }

    /**
     * @return string
     */
    public function getClientEmail()
    {
        return $this->client_email;
    }

    /**
     * @param string $client_email
     */
    public function setClientEmail($client_email)
    {
        $this->client_email = $client_email;
    }



    /**
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * @param string $checksum
     */
    public function setChecksum($checksum)
    {
        $this->checksum = $checksum;
    }

    /**
     * @return Rate
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * @param Rate
     * @return Survey
     */
    public function setRate(Rate $rate)
    {
        $this->rate = $rate;
        return $this;
    }

    /**
     * @return SurveyStaffRate
     */
    public function getStaffRate()
    {
        return $this->staff_rate;
    }

    /**
     * @param SurveyStaffRate $staff_rate
     * @return Survey
     */
    public function setStaffRate(SurveyStaffRate $staff_rate)
    {
        $this->staff_rate = $staff_rate;

        return $this;
    }

    /**
     * @return Rate
     */
    public function getResendRate()
    {
        return $this->resend_rate;
    }

    /**
     * @param Rate $resend_rate
     * @return Survey
     */
    public function setResendRate(Rate $resend_rate)
    {
        $this->resend_rate = $resend_rate;

        return $this;
    }

    /**
     * @return SurveyStaffRate
     */
    public function getResendStaffRate()
    {
        return $this->resend_staff_rate;
    }

    /**
     * @param SurveyStaffRate $resend_staff_rate
     * @return Survey
     */
    public function setResendStaffRate(SurveyStaffRate $resend_staff_rate)
    {
        $this->resend_staff_rate = $resend_staff_rate;

        return $this;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    }

    /**
     * @return string
     */
    public function getResendComment()
    {
        return $this->resend_comment;
    }

    /**
     * @param string $resend_comment
     */
    public function setResendComment($resend_comment)
    {
        $this->resend_comment = $resend_comment;
    }

    /**
     * @return string
     */
    public function getUserComment()
    {
        return $this->user_comment;
    }

    /**
     * @param string $user_comment
     */
    public function setUserComment($user_comment)
    {
        $this->user_comment = $user_comment;
    }

    /**
     * @return boolean
     */
    public function isCancel()
    {
        return $this->cancel;
    }

    /**
     * @param boolean $cancel
     */
    public function setCancel($cancel)
    {
        $this->cancel = $cancel;
    }

    /**
     * @return string
     */
    public function getAdminComment()
    {

src/SurveyBundle/Entity/SurveyType.php
<?php

namespace SurveyBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * SurveyType
 *
 * @ORM\Table(name="survey_type")
 * @ORM\Entity(repositoryClass="SurveyBundle\Repository\SurveyTypeRepository")
 */
class SurveyType
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255, unique=true)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="count_module", type="string", length=255)
     */
    private $countModule;

    /**
     * @var boolean
     * @ORM\Column(name="extra_question", type="boolean")
     */
    private $extraQuestions;

    /**
     * @ORM\OneToMany(targetEntity="SurveyBundle\Entity\Survey",mappedBy="survey_type")
     */
    private $survey;

    /**
     * @ORM\OneToMany(targetEntity="SurveyBundle\Entity\Rate",mappedBy="survey_type")
     */
    private $rate;

    public function __construct()
    {
        $this->survey = new ArrayCollection();
        $this->rate = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     *
     * @return SurveyType
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set countModule
     *
     * @param string $countModule
     *
     * @return SurveyType
     */
    public function setCountModule($countModule)
    {
        $this->countModule = $countModule;

        return $this;
    }

    /**
     * Get countModule
     *
     * @return string
     */
    public function getCountModule()
    {
        return $this->countModule;
    }

    /**
     * Add surveyId
     *
     * @param \SurveyBundle\Entity\Survey $survey
     *
     * @return SurveyType
     */
    public function addSurvey(\SurveyBundle\Entity\Survey $survey)
    {
        $this->survey[] = $survey;

        return $this;
    }

    /**
     * Remove surveyId
     *
     * @param \SurveyBundle\Entity\Survey $survey
     */
    public function removeSurvey(\SurveyBundle\Entity\Survey $survey)
    {
        $this->survey->removeElement($survey);
    }

    /**
     * Get surveyId
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSurvey()
    {
        return $this->survey;
    }

    public function __toString()
    {
        return $this->getType();
    }

    /**
     * Add rate
     *
     * @param \SurveyBundle\Entity\Rate $rate
     *
     * @return SurveyType
     */
    public function addRate(\SurveyBundle\Entity\Rate $rate)
    {
        $this->rate[] = $rate;

        return $this;
    }

    /**
     * Remove rate
     *
     * @param \SurveyBundle\Entity\Rate $rate
     */
    public function removeRate(\SurveyBundle\Entity\Rate $rate)
    {
        $this->rate->removeElement($rate);
    }

    /**
     * Get rate
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * @return boolean
     */
    public function isExtraQuestions()
    {
        return $this->extraQuestions;
    }

    /**
     * @param boolean $extraQuestions
     */
    public function setExtraQuestions($extraQuestions)
    {
        $this->extraQuestions = $extraQuestions;
    }

    /**
     * Get extraQuestions
     *
     * @return boolean
     */
    public function getExtraQuestions()
    {
        return $this->extraQuestions;
    }
}

src/SurveyBundle/Form/SurveyType.php
<?php
/**
 * Created by PhpStorm.
 * User: muszkin
 * Date: 16.11.16
 * Time: 09:24
 */

namespace SurveyBundle\Form;


use SurveyBundle\Entity\Survey;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SurveyType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if (in_array('ROLE_ADMIN',$options['roles'])){
            $builder
                ->add('sendDate',DateTimeType::class,[
                    'label' => 'Survey send date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('openDate',DateTimeType::class,[
                    'label' => 'Survey open date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('voteDate',DateTimeType::class,[
                    'label' => 'Survey vote date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('resendDate',DateTimeType::class,[
                    'label' => 'Survey resend date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('resendOpenDate',DateTimeType::class,[
                    'label' => 'Survey resend open date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('resendVoteDate',DateTimeType::class,[
                    'label' => 'Survey resend vote date',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('rate',IntegerType::class,[
                    'label' => 'Survey rate',
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('resendRate',IntegerType::class,[
                    'label' => 'Survey resend rate',
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])
                ->add('comment',TextType::class,[
                    'label' => 'Client comment',
                    'attr' => [
                        'class' => 'form-control',
                    ],
                ])
                ->add('resendComment',TextType::class,[
                    'label' => 'Client resend comment',
                    'attr' => [
                        'class' => 'form-control'
                    ],
                ])

            ;
        }



        $builder
            ->add('submit',SubmitType::class,[
                'label' => 'Save'
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "data_class" => Survey::class,
            "roles" => ['ROLE_USER'],
            'translation_domain' => 'SurveyBundle',
        ]);
    }

}

src/SurveyBundle/Resources/views/panel/survey/cancel.html.twig
<div class="container-fluid">
    <div class="row">
        <div class="input-group-lg input-group m-2">
            <label for="user_comment">Describe your request</label>
            <textarea rows="4" class="form-control" id="user_comment"></textarea>
        </div>

    </div>
    <div class="row">
        <button type="button" class="btn btn-success cancel-send" data-dismiss="modal" data-url="{{ path('survey_cancel_request',{'survey':survey.id}) }}">
            Send cancel request
        </button>
    </div>
</div>

src/SurveyBundle/Resources/views/panel/survey/index.html.twig
{% extends '@Survey/panel/index.html.twig' %}
{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                All surveys {{ pagination.getTotalItemCount }}
                <br/>
                {% if filters is defined %}
                {% include '@Survey/panel/filters.html.twig' %}
                {% block filters %}
                {% endblock %}
                {% endif %}
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
            <div class="panel-body">

                <table class="table table-bordered table-striped table-hover table-responsive">
                    <thead class="thead-default">
                    <th>Id</th>
                    <th>Ticket id</th>
                    <th>Post id</th>
                    <th>Client email</th>
                    <th>Client id</th>
                    <th>Type</th>
                    <th>Send date</th>
                    <th>Open date</th>
                    <th>Vote date</th>
                    <th>Resend date</th>
                    <th>Resend open date</th>
                    <th>Resend vote date</th>
                    <th>Rate</th>
                    <th>Resend rate</th>
                    <th>Comment</th>
                    <th>Resend comment</th>
                    <th>User comment</th>
                    <th>Admin comment</th>
                    </thead>
                    <tbody>
                    {% for survey in pagination %}
                        <tr>
                            <td scope="row"><a href="{{ path('survey_edit',{'survey':survey.id}) }}">{{ survey.id }}</a></td>
                            <td>
                                {% if survey.ticketId is not null %}
                                    {{ survey.ticketId }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.postId is not null %}
                                    {{ survey.postId }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.clientEmail is not null %}
                                    {{ survey.clientEmail }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.clientId is not null %}
                                    {{ survey.clientId }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.surveyType is not null %}
                                    {{ survey.surveyType }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.sendDate is not null %}
                                    {{ survey.sendDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.openDate is not null %}
                                    {{ survey.openDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.voteDate is not null %}
                                    {{ survey.voteDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.resendDate is not null %}
                                    {{ survey.resendDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.resendOpenDate is not null %}
                                    {{ survey.resendOpenDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.resendVoteDate is not null %}
                                    {{ survey.resendVoteDate|date("Y-m-d H:i:s") }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.rate is not null %}
                                    {{ survey.rate }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.resendRate is not null %}
                                    {{ survey.resendRate }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.comment is not null %}
                                    {{ survey.comment }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.resendComment is not null %}
                                    {{ survey.resendComment }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.userComment is not null %}
                                    {{ survey.userComment }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.adminComment is not null %}
                                    {{ survey.adminComment }}
                                {% else %}
                                    {% if survey.cancel %}
                                        <span class="red">Canceled</span>
                                    {% else %}
                                        <span class="red">Not canceled</span>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td>
                                {% if survey.voteDate is not null %}
                                    {% set difference = date('now').diff(date(survey.voteDate)) %}
                                    {% set leftDays = difference.days %}
                                        {% if leftDays <= 3
                                        and survey.resendDate is null
                                        and survey.resendOpenDate is null
                                        and survey.resendVoteDate is null
                                        and survey.resendRate is null %}
                                            <button type="button" data-url="{{ path('survey_resend_request', { 'survey' : survey.id}) }}" class="btn btn-danger btn-lg resend" data-toggle="modal" data-target="#resend">
                                                {{ 'Resend survey' | trans }}
                                            </button>
                                        {% endif %}
                                {% endif %}
                                {% if survey.voteDate is not null %}
                                    {% set difference = date('now').diff(date(survey.voteDate)) %}
                                    {% set leftDays = difference.days %}
                                    {% if leftDays <= 30 and survey.userComment is null %}
                                        <button type="button" data-url="{{ path('survey_cancel_request', { 'survey' : survey.id}) }}" class="btn btn-danger btn-lg cancel" data-toggle="modal" data-target="#cancel">
                                            {{ 'Cancel request' | trans }}
                                        </button>
                                    {% endif %}
                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="cancel" class="modal fade" tabindex="-1" role="alertdialog" aria-labelledby="modal_label">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="modal-label">Cancel request</h4>
                            </div>
                            <div class="modal-body cancel-body" id="modal-content">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
                <div id="resend" class="modal fade" tabindex="-1" role="alertdialog" aria-labelledby="modal_label">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="modal-label">Resend request</h4>
                            </div>
                            <div class="modal-body resend-body" id="modal-content">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
                <a href="{{ path('index') }}" class="btn btn-bg btn-info">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

src/SurveyBundle/Resources/views/panel/survey/resend.html.twig
<div class="container-fluid">
    <div class="row">
        <div class="input-group-lg input-group m-2">
            <label for="contact">Type of contact</label>
            <select name="contact" id="contact" class="form-control">
                <option value="phone">Phone</option>
                <option value="email">Email</option>
            </select>
        </div>
        <div class="input-group-lg input-group m-2">
            <label for="contact_date">Date of contact</label>
            <input type="datetime" name="contact_date" id="contact_date" class="form-control">
        </div>
        <div class="input-group-lg input-group m-2">
            <label for="user_comment">Describe your request</label>
            <textarea rows="4" class="form-control" id="user_comment"></textarea>
        </div>
    </div>
    <div class="row">
        <button type="button" class="btn btn-success resend-send" data-dismiss="modal" data-url="{{ path('survey_resend_request',{'survey':survey.id}) }}">
            Resend survey
        </button>
    </div>
</div>