src/SurveyBundle/Entity/Survey.php
<?php

namespace SurveyBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Survey
 *
 * @ORM\Table(name="survey")
 * @ORM\Entity(repositoryClass="SurveyBundle\Repository\SurveyRepository")
 */
class Survey
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\User",inversedBy="survey_id",cascade={"persist"})
     * @ORM\JoinColumn(name="user_id",referencedColumnName="id")
     */
    private $user_id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="send_date",type="datetime")
     */
    private $send_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="open_date",type="datetime",nullable=true)
     */
    private $open_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="vote_date",type="datetime",nullable=true)
     */
    private $vote_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_date",type="datetime",nullable=true)
     */
    private $resend_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_open_date",type="datetime",nullable=true)
     */
    private $resend_open_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="resend_vote_date",type="datetime",nullable=true)
     */
    private $resend_vote_date;

    /**
     * @var int
     * @ORM\Column(name="ticket_id",type="integer",length=11,nullable=true)
     */
    private $ticket_id;

    /**
     * @var int
     * @ORM\Column(name="post_id",type="integer",length=11,nullable=true)
     */
    private $post_id;

    /**
     * @var int
     * @ORM\Column(name="client_id",type="integer",length=11,nullable=true)
     */
    private $client_id;

    /**
     * @var string
     * @ORM\Column(name="client_email",type="string")
     */
    private $client_email;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyType",inversedBy="survey",cascade={"persist"})
     * @ORM\JoinColumn(name="survey_type",referencedColumnName="id")
     */
    private $survey_type;

    /**
     * @var string
     * @ORM\Column(name="checksum",type="string")
     */
    private $checksum;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\Rate",inversedBy="survey")
     * @ORM\JoinColumn(name="rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $rate;

    /**
     * @var SurveyStaffRate
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyStaffRate",inversedBy="survey")
     * @ORM\JoinColumn(name="staff_rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $staff_rate;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\Rate",inversedBy="survey_resend")
     * @ORM\JoinColumn(name="resend_rate",referencedColumnName="id",columnDefinition="INT NULL")
     */
    private $resend_rate;

    /**
     * @var SurveyStaffRate
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\SurveyStaffRate",inversedBy="survey_second")
     * @ORM\JoinColumn(name="resend_staff_rate",referencedColumnName="id",columnDefinition=" INT NULL")
     */
    private $resend_staff_rate;

    /**
     * @var string
     * @ORM\Column(name="comment",type="text",nullable=true)
     */
    private $comment;

    /**
     * @var string
     * @ORM\Column(name="resend_comment",type="text",nullable=true)
     */
    private $resend_comment;

    /**
     * @var string
     * @ORM\Column(name="user_comment",type="text",nullable=true)
     */
    private $user_comment;

    /**
     * @var boolean
     * @ORM\Column(name="cancel",type="boolean",nullable=true)
     */
    private $cancel;

    /**
     * @var string
     * @ORM\Column(name="admin_comment",type="text",nullable=true)
     */
    private $admin_comment;

    /**
     * @ORM\OneToOne(targetEntity="SurveyBundle\Entity\SurveyResend",mappedBy="survey")
     */
    private $resend;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param User $user_id
     *
     * @return mixed
     */
    public function setUserId(\SurveyBundle\Entity\User $user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getSendDate()
    {
        return $this->send_date;
    }

    /**
     * @param \DateTime $send_date
     */
    public function setSendDate($send_date)
    {
        $this->send_date = $send_date;
    }

    /**
     * @return \DateTime
     */
    public function getOpenDate()
    {
        return $this->open_date;
    }

    /**
     * @param \DateTime $open_date
     */
    public function setOpenDate($open_date)
    {
        $this->open_date = $open_date;
    }

    /**
     * @return \DateTime
     */
    public function getVoteDate()
    {
        return $this->vote_date;
    }

    /**
     * @param \DateTime $vote_date
     */
    public function setVoteDate($vote_date)
    {
        $this->vote_date = $vote_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendDate()
    {
        return $this->resend_date;
    }

    /**
     * @param \DateTime $resend_date
     */
    public function setResendDate($resend_date)
    {
        $this->resend_date = $resend_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendOpenDate()
    {
        return $this->resend_open_date;
    }

    /**
     * @param \DateTime $resend_open_date
     */
    public function setResendOpenDate($resend_open_date)
    {
        $this->resend_open_date = $resend_open_date;
    }

    /**
     * @return \DateTime
     */
    public function getResendVoteDate()
    {
        return $this->resend_vote_date;
    }

    /**
     * @param \DateTime $resend_vote_date
     */
    public function setResendVoteDate($resend_vote_date)
    {
        $this->resend_vote_date = $resend_vote_date;
    }

    /**
     * @return int
     */
    public function getTicketId()
    {
        return $this->ticket_id;
    }

    /**
     * @param int $ticket_id
     */
    public function setTicketId($ticket_id)
    {
        $this->ticket_id = $ticket_id;
    }

    /**
     * @return int
     */
    public function getPostId()
    {
        return $this->post_id;
    }

    /**
     * @param int $post_id
     */
    public function setPostId($post_id)
    {
        $this->post_id = $post_id;
    }

    /**
     * @return int
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * @param int $client_id
     */
    public function setClientId($client_id)
    {
        $this->client_id = $client_id;
    }

    /**
     * @return string
     */
    public function getClientEmail()
    {
        return $this->client_email;
    }

    /**
     * @param string $client_email
     */
    public function setClientEmail($client_email)
    {
        $this->client_email = $client_email;
    }



    /**
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * @param string $checksum
     */
    public function setChecksum($checksum)
    {
        $this->checksum = $checksum;
    }

    /**
     * @return Rate
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * @param Rate
     * @return Survey
     */
    public function setRate(Rate $rate)
    {
        $this->rate = $rate;
        return $this;
    }

    /**
     * @return SurveyStaffRate
     */
    public function getStaffRate()
    {
        return $this->staff_rate;
    }

    /**
     * @param SurveyStaffRate $staff_rate
     * @return Survey
     */
    public function setStaffRate(SurveyStaffRate $staff_rate)
    {
        $this->staff_rate = $staff_rate;

        return $this;
    }

    /**
     * @return Rate
     */
    public function getResendRate()
    {
        return $this->resend_rate;
    }

    /**
     * @param Rate $resend_rate
     * @return Survey
     */
    public function setResendRate(Rate $resend_rate)
    {
        $this->resend_rate = $resend_rate;

        return $this;
    }

    /**
     * @return SurveyStaffRate
     */
    public function getResendStaffRate()
    {
        return $this->resend_staff_rate;
    }

    /**
     * @param SurveyStaffRate $resend_staff_rate
     * @return Survey
     */
    public function setResendStaffRate(SurveyStaffRate $resend_staff_rate)
    {
        $this->resend_staff_rate = $resend_staff_rate;

        return $this;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    }

    /**
     * @return string
     */
    public function getResendComment()
    {
        return $this->resend_comment;
    }

    /**
     * @param string $resend_comment
     */
    public function setResendComment($resend_comment)
    {
        $this->resend_comment = $resend_comment;
    }

    /**
     * @return string
     */
    public function getUserComment()
    {
        return $this->user_comment;
    }

    /**
     * @param string $user_comment
     */
    public function setUserComment($user_comment)
    {
        $this->user_comment = $user_comment;
    }

    /**
     * @return boolean
     */
    public function isCancel()
    {
        return $this->cancel;
    }

    /**
     * @param boolean $cancel
     */
    public function setCancel($cancel)
    {
        $this->cancel = $cancel;
    }

    /**
     * @return string
     */
    public function getAdminComment()
    {

src/SurveyBundle/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: muszkin
 * Date: 27.10.16
 * Time: 11:26
 */

namespace SurveyBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class User
 * @package SurveyBundle\Entity
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @ORM\AttributeOverrides({
 *  @ORM\AttributeOverride(
 *      name="salt",
 *      column=@ORM\Column(name="salt", type="string", nullable=true)
 *      )
 *  })
 */
class User extends BaseUser
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     * @ORM\Column(name="sid",type="integer",unique=true)
     */
    protected $sid;

    /**
     * @var int
     * @ORM\Column(name="admin_id",type="integer",unique=true)
     */
    protected $admin_id;

    /**
     * @ORM\ManyToOne(targetEntity="SurveyBundle\Entity\Team",inversedBy="user_id",cascade={"persist","remove"})
     * @ORM\JoinColumn(name="team_id",referencedColumnName="id")
     */
    protected $team;

    /**
     * @var string
     * @ORM\Column(name="name",type="string")
     */
    protected $name;

    /**
     * @var int
     * @ORM\OneToMany(targetEntity="SurveyBundle\Entity\Survey",mappedBy="user_id")
     */
    protected $survey_id;

    /**
     * User constructor.
     */

    public function __construct()
    {
        parent::__construct();
        $this->survey_id = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * @param int $sid
     */
    public function setSid($sid)
    {
        $this->sid = $sid;
    }

    /**
     * @return mixed
     */
    public function getAdminId()
    {
        return $this->admin_id;
    }

    /**
     * @param mixed $admin_id
     */
    public function setAdminId($admin_id)
    {
        $this->admin_id = $admin_id;
    }

    /**
     * @return mixed
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * @param mixed $team
     *
     * @return mixed
     */
    public function setTeam(\SurveyBundle\Entity\Team $team = null)
    {
        $this->team = $team;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }


    /**
     * Add surveyId
     *
     * @param \SurveyBundle\Entity\Survey $surveyId
     *
     * @return User
     */
    public function addSurveyId(\SurveyBundle\Entity\Survey $surveyId)
    {
        $this->survey_id[] = $surveyId;

        return $this;
    }

    /**
     * Remove surveyId
     *
     * @param \SurveyBundle\Entity\Survey $surveyId
     */
    public function removeSurveyId(\SurveyBundle\Entity\Survey $surveyId)
    {
        $this->survey_id->removeElement($surveyId);
    }

    /**
     * Get surveyId
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSurveyId()
    {
        return $this->survey_id;
    }
}

src/SurveyBundle/Form/UserType.php
<?php
/**
 * Created by PhpStorm.
 * User: muszkin
 * Date: 08.11.16
 * Time: 12:18
 */

namespace SurveyBundle\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use SurveyBundle\Entity\Team;

class UserType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                    "placeholder" => "Name of new team"
                ],
            ])
            ->add('username',TextType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                    "placeholder" => "Name of module for team"
                ],
            ])
            ->add('team',EntityType::class,[
                "class" => 'SurveyBundle\Entity\Team',
                "label" => "Choose team",
                "attr" => [
                    "class" => 'form-control'
                ],
            ])
            ->add('email',TextType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                    "placeholder" => "Name of new team"
                ],
            ])
            ->add('sid',TextType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                    "placeholder" => "Name of new team"
                ],
            ])
            ->add('admin_id',TextType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                    "placeholder" => "Name of new team"
                ],
            ])
            ->add('password',PasswordType::class,[
                "attr" => [
                    "class" => 'form-control',
                    "aria-describedby" => "sizing-addon1",
                ],
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SurveyBundle\Entity\User',
            'translation_domain' => 'SurveyBundle',
        ));
    }
}

src/SurveyBundle/Resources/views/admin/user/edit.html.twig
{% extends '@Survey/admin/index.html.twig' %}

{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit user {{ user }}
            </div>
            <div class="panel-body">
                {{ form_start(edit_form) }}
                <div class="input-group-lg input-group m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.name) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.username) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.team) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.email) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.sid) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.admin_id) }}
                </div>
                <div class="input-group input-group-lg m-2">
                    <span class="input-group-addon glyphicon glyphicon-triangle-right" id="sizing-addon1"></span>
                    {{ form_widget(edit_form.password) }}
                </div>

                <input type="submit" value="Edit" class="btn btn-bg btn-warn m-2"/>
                {{ form_end(edit_form) }}
                {{ form_start(delete_form) }}
                <input type="submit" value="Delete" class="btn btn-bg btn-danger m-2">
                {{ form_end(delete_form) }}
                <a href="{{ path('showAllUsers') }}" class="btn btn-info m-2">Back to the list</a>
            </div>
        </div>
    </div>
{% endblock %}

src/SurveyBundle/Resources/views/admin/user/list.html.twig
{% extends '@Survey/admin/index.html.twig' %}

{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                User list
                {% if filters is defined %}
                    {% include '@Survey/admin/filters/filters.html.twig' %}
                    {% block filters %}
                    {% endblock %}
                {% endif %}
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped table-hover table-responsive">
                    <thead class="thead-default">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Team</th>
                        <th>E-mail</th>
                        <th>Staff Id (Kayako)</th>
                        <th>Admin id (admin.shoper.pl)</th>
                        <th>Reply rating</th>
                        <th>Nps rating</th>
                        <th>Phone rating</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <th scope="row">{{ user.id }}</th>
                            <td>{{ user.name }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.team }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.sid }}</td>
                            <td>{{ user.adminId }}</td>
                            <td>{{ ratings[user.id].reply.rate |round(2)}}% ({{ ratings[user.id].reply.votes }})</td>
                            <td>{{ ratings[user.id].nps.rate |round(2)}} ({{ ratings[user.id].nps.votes }})</td>
                            <td>{{ ratings[user.id].phone_in.rate|round(2) }} ({{ ratings[user.id].phone_in.votes }})</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle glyphicon glyphicon-cog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ path('show_user', { 'id': user.id }) }}">Show</a></li>
                                        <li><a href="{{ path('user_edit', { 'id': user.id }) }}">Edit</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <a href="{{ path('user_new') }}" class="btn btn-bg btn-danger">Create a new user</a>
            </div>
        </div>


    </div>
{% endblock %}

src/SurveyBundle/Resources/views/admin/user/show.html.twig
{% extends '@Survey/admin/index.html.twig' %}
{% trans_default_domain 'SurveyBundle' %}

{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                User info for {{ user.name }}
                <br/>
                {% include '@Survey/admin/filters.html.twig' %}
                {% block filters %}
                {% endblock %}
                <div>
                    {{ "Ratings"|trans }}
                    <strong>Nps: {{ ratings.nps.rate |round(2)}} ({{ ratings.nps.votes }})</strong>
                    <strong>Reply: {{ ratings.reply.rate |round(2)}}% ({{ ratings.reply.votes }})</strong>
                    <strong>Phone: {{ ratings.phone_in.rate |round(2)}} ({{ ratings.phone_in.votes }})</strong>
                </div>
                All surveys: {{ pagination.getTotalItemCount }}
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
            <div class="panel-body">
                    <table class="table table-bordered table-striped table-hover table-responsive">
                        <thead class="thead-default">
                            <th>Id</th>
                            <th>Ticket id</th>
                            <th>Post id</th>
                            <th>Client id</th>
                            <th>Type</th>
                            <th>Send date</th>
                            <th>Open date</th>
                            <th>Vote date</th>
                            <th>Resend date</th>
                            <th>Resend open date</th>
                            <th>Resend vote date</th>
                            <th>Rate</th>
                            <th>Resend rate</th>
                            <th>Comment</th>
                            <th>Resend comment</th>
                            <th>User comment</th>
                            <th>Admin comment</th>
                        </thead>
                        <tbody>
                        {% for survey in pagination %}
                            <tr {% if survey.adminComment is not null %} style="color:red;"{% endif %}>
                                <td scope="row">{{ survey.id }}</td>
                                <td>
                                    {% if survey.ticketId is not null %}
                                        <a href="https://pomoc.shoper.pl/staff/index.php?/Tickets/Ticket/View/{{ survey.ticketId }}" target="_blank">{{ survey.ticketId }}</a>
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.postId is not null %}
                                        <a href="https://pomoc.shoper.pl/staff/index.php?/Tickets/Ticket/View/{{ survey.ticketId }}/#{{ survey.postId }}" target="_blank">{{ survey.postId }}</a>
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.clientId is not null %}
                                        <a href="https://admin.shoper.pl/admin/client/edit/id/{{ survey.clientId }}" target="_blank">{{ survey.clientId }}</a>
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.surveyType is not null %}
                                        {{ survey.surveyType }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.sendDate is not null %}
                                        {{ survey.sendDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.openDate is not null %}
                                        {{ survey.openDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.voteDate is not null %}
                                        {{ survey.voteDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.resendDate is not null %}
                                        {{ survey.resendDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.resendOpenDate is not null %}
                                        {{ survey.resendOpenDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.resendVoteDate is not null %}
                                        {{ survey.resendVoteDate|date("Y-m-d H:i:s") }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.rate is not null %}
                                        {{ survey.rate }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.resendRate is not null %}
                                        {{ survey.resendRate }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.comment is not null %}
                                        {{ survey.comment }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.resendComment is not null %}
                                        {{ survey.resendComment }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.userComment is not null %}
                                        {{ survey.userComment }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if survey.adminComment is not null %}
                                        {{ survey.adminComment }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                <a href="{{ path('showAllUsers') }}" class="btn btn-bg btn-info">Back to user list</a>
            </div>
        </div>
    </div>
{% endblock %}